### ISSUE TITLE
你的这版本

### ISSUE THREAD

**Issue by i0sdev** [wongsyrone/ocserv-cn-no-route#1]
使用上是不是先把generate-ocserv-no-route.sh和merge-cidr.pl下载到本地，然后bash哪个脚本？

**Comment by wongsyrone** [comment]
两个放在同目录，都加上可执行权限，最后bash .sh文件

**Comment by i0sdev** [comment]
最后的文件和原来的对比了下，还是有些不一样，有的ip段少了些，有的多了些。是什么原因？哪个版本更合理你点？
