### ISSUE TITLE
版本比较

### ISSUE THREAD

**Issue by i0sdev** [wongsyrone/ocserv-cn-no-route#2]
最后的文件和原来CNMan的对比了下，还是有些不一样，有的ip段少了些，有的多了些。是什么原因？哪个版本更合理你点？

**Comment by wongsyrone** [comment]
你可以看代码，操作步骤是按照他描述的那样写的，其中排序部分是sort命令，合并部分使用的是perl的一个模块: Net::CIDR::Lite，是专门做cidr合并的，perl脚本里面就是使用的模块提供的方法，而且由于路由表增加，相近的段会合并或者拆分，这个应该是正常的。我不知道CNMan是怎么做的合并，我这个如果合并有问题也是perl模块的问题，这种情况不太可能发生。如果你用ubuntu的话，我记得有一个可以合并cidr的工具，你也可以测试对比一下。如果有更好的欢迎发PR

**Comment by i0sdev** [comment]
厉害
![image](https://cloud.githubusercontent.com/assets/4564129/10595994/7283b328-7711-11e5-9f82-b32da2363178.png)
