### ISSUE TITLE
手机 safari 登录 qq mail web 好像不起作用

### ISSUE THREAD

**Issue by i0sdev** [wongsyrone/ocserv-cn-no-route#4]
用了你的这个生成的 no-route，手机 safari 登录 qq mail web 还是能收到异地登陆提醒，侦测到通过 vps 的 ip （美国） 去登录。

CNMan 那里的版本也有这个问题。

这个问题有可能对QQ的部分IP，比如微信的也有影响，有时候特别慢。

**Comment by wongsyrone** [comment]
自己查查dns解析的结果，腾讯有国外的服务器的，如果需要，自己做排除
